### ISSUE TITLE
Driver issue?

### ISSUE THREAD

**Issue by Originn** [HellAmbro/Trading212API#11]
When executing `trading212.get_portfolio_composition()` I get the following error:

`selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x55bb3ede4ad3 <unknown>
#1 0x55bb3eb44568 <unknown>
#2 0x55bb3eb7ac46 <unknown>
#3 0x55bb3eb7ae01 <unknown>
#4 0x55bb3ebada64 <unknown>
#5 0x55bb3eb9861d <unknown>
#6 0x55bb3ebab824 <unknown>
#7 0x55bb3eb984e3 <unknown>
#8 0x55bb3eb6dd1a <unknown>
#9 0x55bb3eb6ee75 <unknown>
#10 0x55bb3ee12efd <unknown>
#11 0x55bb3ee2c19b <unknown>
#12 0x55bb3ee14c65 <unknown>
#13 0x55bb3ee2cec8 <unknown>
#14 0x55bb3ee08360 <unknown>
#15 0x55bb3ee48a68 <unknown>
#16 0x55bb3ee48be8 <unknown>
#17 0x55bb3ee627fd <unknown>
#18 0x7fcecebe9609 <unknown>`

Any idea what is wrong? The driver is set up correctly and I can get into website and print the header etc, so I am guessing it's not related to driver setup. I can also login to my 212 account as I get the login notification.

**Comment by HellAmbro** [comment]
Hi, can you please provide the version of your driver?

**Comment by Originn** [comment]
Sure, I am using Google Chrome 100.0.4896.88

**Comment by HellAmbro** [comment]
Thanks.
It's a TimeoutException so maybe something was changed in Trading212 web page and the software it's not able to click or find it. I will investigate asap and let you know about the problem.
Thanks for reporting the issue.

**Comment by HellAmbro** [comment]
I've spotted the error, please let me know if it's work now. 
Thanks for reporting.
