### ISSUE TITLE
find_element removed 

### ISSUE THREAD

**Issue by klllo** [HellAmbro/Trading212API#13]
im getting this error: AttributeError: 'WebDriver' object has no attribute 'find_element_by_class_name'
apperently 'find_ellement' was removed in version 4,3 
Selenium 4.3.0
* Deprecated find_element_by_* and find_elements_by_* are now removed (#10712)
* Deprecated Opera support has been removed (#10630)
* Fully upgraded from python 2x to 3.7 syntax and features (#10647)
* Added a devtools version fallback mechanism to look for an older version when mismatch occurs (#10749)
* Better support for co-operative multi inheritance by utilising super() throughout
* Improved type hints throughout

**Comment by HellAmbro** [comment]
Hi, i will fix it asap, as a workaround you can use an older version of selenium.
