### ISSUE TITLE
Cannot change to live account

### ISSUE THREAD

**Issue by Adam48521** [HellAmbro/Trading212API#15]
I'd like to use this API to extract the data in my live account and not my practice account - how can this be done?
I can see the 'Mode=Mode.DEMO' section of the Trading212 function but haven't been able to find what this should be for the live account instead.

Thanks

**Comment by HellAmbro** [comment]
Hi, try to use this `trading212 = Trading212('myemail', 'mypass', driver, mode=Mode.LIVE)`, just change mode=Mode.DEMO with mode=Mode.LIVE.
Please use live mode with caution, nor me or Trading212 are responsible for money loss.

**Comment by HellAmbro** [comment]
For further questions or help contact me by email or social media, i will be happy to help you. You can find my contacts in my homepage.
