### ISSUE TITLE
Portfolio composition missing average price

### ISSUE THREAD

**Issue by Adam48521** [HellAmbro/Trading212API#18]
Hi,

Please could you update the portfolio function to include the (weighted) average purchase price of the share?
Currently you can work out the average with the quantity of the shares purchased (y) and the total value invested (x), but x/y does not give you the weighted average purchase price. This data is provided by T212, so hopefully it can be incorporated into your scraping.

portfolio = trading212.get_portfolio_composition()

Thanks,
Adam

**Comment by HellAmbro** [comment]
Hi,
I don't want to touch Trading212 response, can you do it on your own?
