### ISSUE TITLE
Maintenance / contributions

### ISSUE THREAD

**Issue by fradeve** [HellAmbro/Trading212API#2]
Hi @HellAmbro, thank you so much for publishing this... it helps a lot!
I was wondering if you are willing to take in some very easy PRs if I submit them,
mostly related to code styling (PEP8), the integration with Pandas and a simple
update to the README.

Thanks again

**Comment by HellAmbro** [comment]
Hi, of course, in this period I do not have too much time to devote to it but it'is not a dead project, so any contribution is welcome. Feel free to contribute.

**Comment by fradeve** [comment]
That's great, thanks @HellAmbro --> I think you can safely close this issue and I will open PRs as soon as I get some time :)

**Comment by HellAmbro** [comment]
In addition, many parts of the code have been written hastily and need more accurate refactoring and review. In other words there is still a lot of work to be done.
