### ISSUE TITLE
Script does not login automatically/ work at all

### ISSUE THREAD

**Issue by bjornstevens** [HellAmbro/Trading212API#20]
I don't know if this script (example.py) still works, but I am stuck right now at the login screen/allow cookies screen.
It shows the following page for about 2 seconds before then closing out and saying:
![afbeelding](https://user-images.githubusercontent.com/23235234/203138909-1d887c6f-7dc6-4d22-bec4-8e863448fbc4.png)

![afbeelding](https://user-images.githubusercontent.com/23235234/203138471-cb1775d8-573d-4e4c-a59b-cabcd2e51350.png)

I am running a brand new Ubuntu 20.04.5 LTS
Using Python3.8.10

**Comment by bjornstevens** [comment]
And for what I am trying to achieve: trading with my demo account.

**Comment by HellAmbro** [comment]
Hi, thanks for contributing, it seems that  T212 changed the class name of the cookies button, also the login button class name.
I want to thank you again and inform you that the bug has been fixed. Update the package to the latest version from PyPi or clone this repo.
For further support please feel free to contact me.

**Comment by bjornstevens** [comment]
Maybe in addition to this, I wonder what version I need of urllib3 or chardet, as it does not seem to work. 
![afbeelding](https://user-images.githubusercontent.com/23235234/203171366-b6c5950a-9ea6-4240-a5e9-a363bc4495e8.png)

**Comment by osaidz** [comment]
Hi, I'm facing the same issue. Has T212 chnaged the class name again?

**Comment by HellAmbro** [comment]
> Hi, I'm facing the same issue. Has T212 chnaged the class name again?

Yes, I've updated the API yesterday, try the latest version. I'm looking for a workaround to bypass this problem.
