### ISSUE TITLE
execute_value_order returns {'code': 'InternalError'}

### ISSUE THREAD

**Issue by LucyBarron** [HellAmbro/Trading212API#22]

**Comment by HellAmbro** [comment]
Hi, can i have more information about this problem? It seems that you forgot to pass some mandatory value in the request. I need to see your code to spot the error.

**Comment by LucyBarron** [comment]
My code is the same as your example code but using 'TSLA'. Apologies, I should have said this.

	value_buy_order = trading212.execute_value_order(
		ValueOrder('TSLA', value=200))

I have just tried using 'TSLA_US_EQ' instead and that seems to work.
