### ISSUE TITLE
CFDOrder class missing from __init__.py

### ISSUE THREAD

**Issue by FinMcLees** [HellAmbro/Trading212API#29]
An error is thrown when attempting to import CFDOrder from pytrading212
__init__.py is missing the CFDOrder class module from .order

Trialled locally adding the class into the __init__.py file with success:
`from .order import EquityOrder, MarketOrder, LimitOrder, StopOrder, StopLimitOrder, ValueOrder, CFDMarketOrder, \
    CFDLimitStopOrder, CFDOCOOrder, CFDOrder`

**Comment by HellAmbro** [comment]
Hi, are you trying to init a `CFDOrder` class directly?
