### ISSUE TITLE
access denied in headless mode 

### ISSUE THREAD

**Issue by klllo** [HellAmbro/Trading212API#30]
when running your api in headless mode with chrome trading 212 will give me this screen 
![Image](https://github.com/HellAmbro/Trading212API/assets/111280845/e7ff6ad0-9319-4a2d-9842-7bcba783bc27)
when i dont use headless mode everything is fine. is this normal?

**Comment by HellAmbro** [comment]
Thanks for reporting, I'll give a look asap.
