### ISSUE TITLE
Not able to trade

### ISSUE THREAD

**Issue by ozammo13** [HellAmbro/Trading212API#31]
Logs in fine but then im slapped with this error:
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <div class="account-menu-info">...</div> is not clickable at point (1329, 30). Other element would receive the click: <div id="platform-loader" class="cfd fade-in fade-out">...</div>

**Comment by HellAmbro** [comment]
Hi, thanks for reporting, i will look asap.

**Comment by dalmeida80** [comment]
Hello , any news about this?
