### ISSUE TITLE
Is there a way to specify the maximum quantity possible when executing a buy market order? 

### ISSUE THREAD

**Issue by JohnPratt5464** [HellAmbro/Trading212API#33]
In the GUI you just slide the slider all the way to the right, is there a way to send a market order to buy the max possible n. of shares/value if the stock can do fractional shares?

**Comment by HellAmbro** [comment]
Hi, yes you can, [min_max_sell_buy](https://github.com/HellAmbro/Trading212API/blob/fc60717b52fa2f2185bd0ebabe130a30ee3d5d9d/pytrading212/trading212.py#L292)
If you call this method 
```python
response = equity.min_max_sell_buy(instrument_code="AAPL_US_EQ")
```
you got a response like this
```json
{
    "minBuy": 1.00,
    "maxBuy": 43865.48,
    "minSell": 1.00,
    "maxSell": 0.00,
    "sellThreshold": 0.00,
    "maxSellQuantity": 0E-8
}
```
convert the response in a python dictionary
```python
minmax_dict = json.loads(response)
```
now you can access the values with
```python
maxBuy =minmax_dict[ "maxBuy"]
```
Now place an order and specify `quantity=maxBuy`
PS: rename the variables as you want
Hope it was helpful.

**Comment by JohnPratt5464** [comment]
Awesome thanks,

One more thing, srry. When I sell a US equity in T212, it sells to dollars. I set it to do this in the settings (sell in the equity's currency). However when I do it through the equity.execute etc. it sells to £. Is there a way to change this?

**Comment by JohnPratt5464** [comment]
Sorry one more thing.

When I sell it sells in £, even when its a US equity. How can I get it to sell in the equity's currency e.g. dollars? I've set it to do so in the settings but it doesn't seem to work.

**Comment by HellAmbro** [comment]
Thanks for reporting. 
Most likely this is because the latest version of the API was developed before that Trading212 introduced the multi-currency account so i think it is using the default currency. As soon as possible I will try to introduce multi-currency support.
