### ISSUE TITLE
got multiple values for argument 'mode'

### ISSUE THREAD

**Issue by wyne1** [HellAmbro/Trading212API#5]
Hello, 

I am trying to use your trading212 API on mac but I keep getting this error related to the mode argument. I am not sure what's going on here, because the Mode.DEMO argument seems to be returning the correct results. 

Would really appreciate any help.

Regards

**Comment by HellAmbro** [comment]
Hi, can you please share the stacktrace of the error?

**Comment by wyne1** [comment]
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-47675501f558> in <module>
     23     # driver = webdriver.Firefox()
     24 
---> 25     trading212 = Trading212(email, password, driver, mode="<Mode.DEMO: (0,)>")
     26 
     27     market_order = trading212.execute_order(

TypeError: __init__() got multiple values for argument 'mode'
```

This is what it shows. Is this what you meant by stacktrace of error?

**Comment by HellAmbro** [comment]
Hi, thanks for reporting bug, can you please clone again this repository and let me now if the error persists. Note: clone this repository don't use pip for now. If you are missing dependencies i've added requirements.txt

**Comment by wyne1** [comment]
Alright, I will try to clone and use it and let you know if the issue persists. Thanks!

**Comment by HellAmbro** [comment]
Let me know
