### ISSUE TITLE
AttributeError: 'Trading212' object has no attribute 'cookie'

### ISSUE THREAD

**Issue by Phalanxguard** [HellAmbro/Trading212API#9]
Downloaded the latest code from the repo, seems like it's having issues getting the session cookie, this had also happened in the previous revision occasionally, but now it seems to be persistent.

  trading212 = Trading212(email, password, driver, mode=Mode.DEMO, trading=Trading.CFD)
  File "C:\Python310\lib\site-packages\pytrading212\trading212.py", line 115, in __init__
  "Cookie": self.cookie,
  AttributeError: 'Trading212' object has no attribute 'cookie'

**Comment by HellAmbro** [comment]
I just tested the code and it seems to be working, try to see the content of the cookie.

`                if cookie['name'] == self.session:
                    self.cookie = f"{self.session}={cookie['value']};"`
the error is related to this line of code, unfortunately there is no session name entry in your cookies. 
Also try to see the value of  `self.session` .
